---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/ubuntu
    groups:
      - zookeeper
  - name: instance2
    image: docker.io/pycontribs/ubuntu
    groups:
      - zookeeper
  - name: instance3
    image: docker.io/pycontribs/ubuntu
    groups:
      - zookeeper
provisioner:
  name: ansible
verifier:
  name: ansible
