---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: jrei/systemd-ubuntu
    groups:
      - zookeeper
provisioner:
  name: ansible
verifier:
  name: ansible
