galaxy_info:
  author: Kroustouris Stavros
  description: This role installs zookeeper on ubuntu
  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.9

  platforms:
  - name: Ubuntu
    versions:
    - 20.04
    - 18.04

  galaxy_tags:
    - zookeeper

dependencies: []
collections:
- community.general
