name: molecule-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  molecule-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with molecule
        run: |
          cd roles/zookeeper; molecule test
